version: "3.8"

services:
  nginx:
    container_name: nginx_rate_limiter
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - express_server
  express_server:
    container_name: express_server
    build:
      context: ./
    ports:
      - "3000:3000"
