version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - "8089:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  express_server:
    container_name: express_server
    build:
      context: ./
    ports:
      - "3000:3000"
